worker_processes auto;

events {
    worker_connections 1024;
}

http {
    map $http_x_core_project $x_appwrite_project {
        default $http_x_appwrite_project;
        ~. $http_x_core_project;
    }

    map $http_x_core_response_format $x_appwrite_response_format {
        default $http_x_appwrite_response_format;
        ~. $http_x_core_response_format;
    }

    map $http_x_core_jwt $x_appwrite_jwt {
        default $http_x_appwrite_jwt;
        ~. $http_x_core_jwt;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://appwrite:80;

            # Standard proxy headers
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            # WebSocket support
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            # Header rewrites
            proxy_set_header X-Appwrite-Project $x_appwrite_project;
            proxy_set_header X-Appwrite-Response-Format $x_appwrite_response_format;
            proxy_set_header X-Appwrite-JWT $x_appwrite_jwt;
        }
    }
} 