version: "3.8"

x-logging: &x-logging
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

services:
  mariadb:
    image: mariadb:10.11
    container_name: x-mariadb
    <<: *x-logging
    restart: unless-stopped
    ports:
      - "3306:3306" # expose MariaDB to host on port 3306
    volumes:
      - appwrite-mariadb:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=Lbyr104!!!Baseball7
      - MYSQL_DATABASE=appwrite
      - MYSQL_USER=lbyron
      - MYSQL_PASSWORD=Lbyr104!!!
      - MARIADB_AUTO_UPGRADE=1
    command: 'mysqld --innodb-flush-method=fsync'

  redis:
    image: redis:7.2.4
    container_name: x-redis
    <<: *x-logging
    restart: unless-stopped
    ports:
      - "6379:6379" # expose Redis to host on port 6379
    volumes:
      - appwrite-redis:/data:rw
    command: >
      redis-server
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --maxmemory-samples 5

volumes:
  appwrite-mariadb:
  appwrite-redis:
